### ISSUE TITLE
遇到了问题

### ISSUE THREAD

**Issue by jxyddtc** [weixuqin/PythonProjects#1]
请问运行代码后返回结果是TypeError: Object type <class 'str'> cannot be passed to C code怎么解决？谢谢！

**Comment by weixuqin** [comment]
请问你运行的是我的哪个 爬虫文件呢

**Comment by jxyddtc** [comment]
运行的是爬取网易云音乐那个，我使用的是python3.6

**Comment by weixuqin** [comment]
应该是没有安装pycrypto这个模块，我自己使用的的 anaconda 发行版，自带有 pycrypto 模块，所有没有注意到这个问题，你可以通过 pip install pycrypto 安装这个模块后再运行爬虫文件试试。

**Comment by jxyddtc** [comment]
好的谢谢♪(･ω･)ﾉ
